version: "3.7"

services:
  sobralacai_db:
    image: supabase/postgres:15.8.1.085
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - sobralacai_net
    volumes:
      - sobralacai_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sobralacai2_db_password_secure_2026
      - POSTGRES_DB=postgres
      - JWT_SECRET=sobralacai2_jwt_secret_key_very_secure_2026
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  sobralacai_auth:
    image: supabase/gotrue:v2.182.1
    networks:
      - sobralacai_net
    depends_on:
      - sobralacai_db
    environment:
      - GOTRUE_API_HOST=0.0.0.0
      - GOTRUE_API_PORT=9999
      - API_EXTERNAL_URL=https://supab2.zedarede.org
      - GOTRUE_DB_DRIVER=postgres
      - GOTRUE_DB_DATABASE_URL=postgres://postgres:sobralacai2_db_password_secure_2026@sobralacai_db:5432/postgres
      - GOTRUE_SITE_URL=https://supab2.zedarede.org
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_JWT_ADMIN_ROLES=service_role
      - GOTRUE_JWT_AUD=authenticated
      - GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
      - GOTRUE_JWT_EXP=31536000
      - GOTRUE_JWT_SECRET=sobralacai2_jwt_secret_key_very_secure_2026
      - GOTRUE_MAILER_AUTOCONFIRM=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  sobralacai_rest:
    image: postgrest/postgrest:v13.0.7
    networks:
      - sobralacai_net
    depends_on:
      - sobralacai_db
    environment:
      - PGRST_DB_URI=postgres://postgres:sobralacai2_db_password_secure_2026@sobralacai_db:5432/postgres
      - PGRST_DB_SCHEMAS=public
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_JWT_SECRET=sobralacai2_jwt_secret_key_very_secure_2026
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  sobralacai_storage:
    image: supabase/storage-api:v1.29.0
    volumes:
      - sobralacai_storage_data:/var/lib/storage:z
    networks:
      - sobralacai_net
    depends_on:
      - sobralacai_db
    environment:
      - ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnJhbGFjYWkyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUwNTA4MDAsImV4cCI6MTg3MjgxNzIwMH0.sobralacai2_anon_key
      - SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnJhbGFjYWkyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNTA1MDgwMCwiZXhwIjoxODcyODE3MjAwfQ.sobralacai2_service_key
      - POSTGREST_URL=http://sobralacai_rest:3000
      - PGRST_JWT_SECRET=sobralacai2_jwt_secret_key_very_secure_2026
      - DATABASE_URL=postgres://postgres:sobralacai2_db_password_secure_2026@sobralacai_db:5432/postgres
      - FILE_SIZE_LIMIT=52428800
      - STORAGE_BACKEND=file
      - FILE_STORAGE_BACKEND_PATH=/var/lib/storage
      - REGION=local
      - TENANT_ID=sobralacai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  sobralacai_api:
    image: kong:2.8.1
    networks:
      - sobralacai_net
    depends_on:
      - sobralacai_auth
      - sobralacai_rest
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong.yml
      - KONG_DNS_ORDER=LAST,A,CNAME
      - KONG_PLUGINS=request-transformer,cors,key-auth,acl,basic-auth,request-termination,ip-restriction
      - JWT_SECRET=sobralacai2_jwt_secret_key_very_secure_2026
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnJhbGFjYWkyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUwNTA4MDAsImV4cCI6MTg3MjgxNzIwMH0.sobralacai2_anon_key
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnJhbGFjYWkyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNTA1MDgwMCwiZXhwIjoxODcyODE3MjAwfQ.sobralacai2_service_key
    volumes:
      - ./kong.yml:/kong.yml:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.sobralacai_api.rule=Host(`supab2.zedarede.org`)
        - traefik.http.services.sobralacai_api.loadbalancer.server.port=8000
        - traefik.http.routers.sobralacai_api.tls=true
        - traefik.http.routers.sobralacai_api.tls.certresolver=letsencryptresolver

  sobralacai_studio:
    image: supabase/studio:2025.11.10-sha-5291fe3
    networks:
      - sobralacai_net
    depends_on:
      - sobralacai_db
    environment:
      - HOSTNAME=0.0.0.0
      - SUPABASE_URL=http://sobralacai_api:8000
      - SUPABASE_PUBLIC_URL=https://supab2.zedarede.org
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnJhbGFjYWkyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUwNTA4MDAsImV4cCI6MTg3MjgxNzIwMH0.sobralacai2_anon_key
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYnJhbGFjYWkyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNTA1MDgwMCwiZXhwIjoxODcyODE3MjAwfQ.sobralacai2_service_key
      - AUTH_JWT_SECRET=sobralacai2_jwt_secret_key_very_secure_2026
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=sobralacai_db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=sobralacai2_db_password_secure_2026
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.sobralacai_studio.rule=Host(`supab2.zedarede.org`) && PathPrefix(`/project`)
        - traefik.http.services.sobralacai_studio.loadbalancer.server.port=3000
        - traefik.http.routers.sobralacai_studio.tls=true
        - traefik.http.routers.sobralacai_studio.tls.certresolver=letsencryptresolver

volumes:
  sobralacai_db_data:
  sobralacai_storage_data:

networks:
  sobralacai_net:
    external: true
    name: sobralacai_net
